CREATE TABLE T_KODE_ARBEIDSFORDELING
(
    KODE      VARCHAR(20) NOT NULL PRIMARY KEY,
    DEKODE    VARCHAR(50),
    FOM_DATO  DATE,
    TOM_DATO  DATE,
    ER_GYLDIG CHAR(1)     NOT NULL,
    BEH_TEMA  VARCHAR(20)
);

CREATE TABLE T_BIDRAG_SAK
(
    SAKSNR              VARCHAR(15)               NOT NULL PRIMARY KEY,
    EIER_FOGD           CHAR(4)                   NOT NULL,
    FOGD_FOM_DATO       DATE                      NOT NULL,
    BIDR_STAT_KODE      VARCHAR(20)               NOT NULL,
    KONV_KODE           VARCHAR(20),
    KONV_DATO           DATE,
    FFU_REF_NR          VARCHAR(20),
    PART_ER_ANSATT      CHAR(1)                   NOT NULL,
    INHABILITET_I_SAK   CHAR(1)                   NOT NULL,
    MYND_KODE           VARCHAR(20),
    OPPRETTET_DATO      DATE                      NOT NULL,
    OPPDRAG_DATO        DATE,
    AVSLUTTET_TIDSPUNKT DATE,
    VEDTAKSPERRE       VARCHAR(30),
    LEVDE_ADSKILT       CHAR(1)                   NOT NULL,
    PARAGRAF_19         CHAR(1)     DEFAULT '0'   NOT NULL,
    SANERT_DATO         DATE,
    KATEGORI_KODE       VARCHAR(10) DEFAULT 'N'   NOT NULL,
    LAND                VARCHAR(30),
    ARBFOR_KODE         VARCHAR(20) DEFAULT 'EEN' NOT NULL
        CONSTRAINT ARBFOR$K
            REFERENCES T_KODE_ARBEIDSFORDELING
);

CREATE TABLE T_ROLLE
(
    ROLLE_ID          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    SAKSNR            VARCHAR(15)                              NOT NULL,
    FNR               CHAR(11),
    SH_IDENT          VARCHAR(20),
    ROLLE_TYPE        VARCHAR(20)                              NOT NULL,
    UKJ_PART_KODE     VARCHAR(20),
    OBJEKTNR          CHAR(2),
    MOTTAGER_ER_VERGE CHAR(1)                                  NOT NULL,
    RM_ROLLE_ID       INTEGER,
    SH_TYPE           VARCHAR(20),
    SH_IDENTTYPE      VARCHAR(20),
    OPPRETTET_DATO    DATE,
    FODT_DATO         DATE
);

CREATE TABLE T_TILGANG_TK
(
    TILGANG_ID       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    SAKSNR           VARCHAR(15)                              NOT NULL,
    TKNR             CHAR(4)                                  NOT NULL,
    TILGANG_FOM_DATO DATE                                     NOT NULL,
    TILGANG_TOM_DATO DATE,
    FOGD_AARSAK_KODE VARCHAR(20)                              NOT NULL,
    TILG_TYPE        VARCHAR(20)                              NOT NULL,
    ARBEIDSFORDELING VARCHAR(200),
    OPPRETTET_AV     VARCHAR(200)
);

CREATE TABLE T_BLANKETT
(
    BLANKETT_ID     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    SAKSNR          VARCHAR(15)                              NOT NULL,
    SOKN_FRA_KODE   VARCHAR(20)                              NOT NULL,
    SOKN_TYPE       VARCHAR(20)                              NOT NULL,
    DOKREF          VARCHAR(20),
    KOMMENTAR       VARCHAR(100),
    FASTSATT_I_LAND VARCHAR(5)
);

CREATE TABLE T_SOKNAD
(
    SOKN_ID                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    BLANKETT_ID             INTEGER                                  NOT NULL
        CONSTRAINT FK_SOKNAD_BLANKETT
            REFERENCES T_BLANKETT,
    SOKN_MOTT_DATO          DATE                                     NOT NULL,
    SOKN_FOM_DATO           DATE,
    SOKN_GR_KODE            VARCHAR(20)                              NOT NULL,
    BEHANDLER_ENHET         CHAR(4),
    SAKSNR                  VARCHAR(15)                              NOT NULL,
    MYNDIGHET               VARCHAR(20),
    FTK_ST_BEH_OK           CHAR(1)                                  NOT NULL,
    FTL_ST_SAMS_INNST       CHAR(1)                                  NOT NULL,
    FTK_ST_DATO             DATE,
    FTK_ST_PRI_TYPE         VARCHAR(20),
    FTK_ST_RES_KODE         VARCHAR(20),
    REF_SOKN_ID             INTEGER,
    BT_SIST_INNHENTET       TIMESTAMP(6),
    INFO_OM_FAR             VARCHAR(5),
    VEDTAKSDATO             DATE,
    NORMDATO                DATE,
    GRUNNLAGSPAKKE_ID       VARCHAR(31),
    LTA_PERIODE_FRA         DATE,
    LTA_PERIODE_TIL         DATE,
    GRUNNLAG_STATUS         VARCHAR(15) DEFAULT 'IKKE_VURDERT'       NOT NULL,
    SIST_OPPDATERT_GRUNNLAG TIMESTAMP(6),
    BEHANDLING_ID           VARCHAR(50)
);

CREATE TABLE T_SOKNAD_LINJE
(
    sokn_linje_id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    sokn_id        INTEGER                                  NOT NULL
        REFERENCES T_SOKNAD,
    sokn_stat_kode VARCHAR(20)                             NOT NULL
);

CREATE TABLE T_HENDELSE
(
    HENDELSE_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    SAKSNR         VARCHAR(15)                              NOT NULL,
    HEND_TYPE      VARCHAR(20)                              NOT NULL,
    OPPRETTET_DATO TIMESTAMP(6)                             NOT NULL,
    ENHET          CHAR(4)                                  NOT NULL,
    SOKN_TYPE      VARCHAR(20),
    RESULTAT       VARCHAR(2000),
    OPPRETTET_AV   VARCHAR(20),
    GR_KOMB_KODE   VARCHAR(20),
    BLANKETT_ID    INTEGER
        CONSTRAINT FK_HENDELSE_BLANKETT
            REFERENCES T_BLANKETT
            ON DELETE SET NULL,
    SOKN_ID        INTEGER
        CONSTRAINT SOKNAID
            REFERENCES T_SOKNAD
            ON DELETE SET NULL,
    FRA_BBM        VARCHAR(20),
    SYS_OPPR_DATO  TIMESTAMP(6) DEFAULT CURRENT TIMESTAMP   NOT NULL
);

CREATE TABLE T_ROLLE_HISTORIKK
(
    ID                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    SAKSNR            VARCHAR(15)                              NOT NULL,
    ROLLE_ID          INTEGER                                  NOT NULL,
    ROLLE_FNR         CHAR(11),
    ROLLE_TYPE        VARCHAR(2),
    RM_ROLLE_ID       INTEGER,
    RM_ROLLE_FNR      CHAR(11),
    TYPE              VARCHAR(50),
    OPPRETTET_AV      VARCHAR(20)                              NOT NULL,
    OPPRETTET_DATO    TIMESTAMP                                NOT NULL
);

INSERT INTO T_KODE_ARBEIDSFORDELING (KODE, DEKODE, FOM_DATO, TOM_DATO, ER_GYLDIG, BEH_TEMA)
VALUES ('BBF', 'Barnebortføring', NULL, NULL, 1, 'ab0323');
INSERT INTO T_KODE_ARBEIDSFORDELING (KODE, DEKODE, FOM_DATO, TOM_DATO, ER_GYLDIG, BEH_TEMA)
VALUES ('EEN', 'Eierenhet', NULL, NULL, 1, NULL);
INSERT INTO T_KODE_ARBEIDSFORDELING (KODE, DEKODE, FOM_DATO, TOM_DATO, ER_GYLDIG, BEH_TEMA)
VALUES ('EFS', 'Ektefellesak', NULL, NULL, 1, 'ab0325');
INSERT INTO T_KODE_ARBEIDSFORDELING (KODE, DEKODE, FOM_DATO, TOM_DATO, ER_GYLDIG, BEH_TEMA)
VALUES ('FRS', 'Farskap', NULL, NULL, 1, 'ab0322');
INSERT INTO T_KODE_ARBEIDSFORDELING (KODE, DEKODE, FOM_DATO, TOM_DATO, ER_GYLDIG, BEH_TEMA)
VALUES ('INH', 'Settekontor', NULL, NULL, 1, NULL);
INSERT INTO T_KODE_ARBEIDSFORDELING (KODE, DEKODE, FOM_DATO, TOM_DATO, ER_GYLDIG, BEH_TEMA)
VALUES ('OPS', 'Oppfostringssak', NULL, NULL, 1, 'ab0324');


-- T_VEDTAK_OVERFORING
CREATE TABLE T_VEDTAK_OVERFORING
(
    id                      INTEGER PRIMARY KEY NOT NULL
        GENERATED BY DEFAULT AS IDENTITY,
    saksnr                  VARCHAR(15)         NOT NULL,
    sokn_id                 INTEGER,
    rolle_hist_id           INTEGER,
    vedtak_timestamp_bisys  TIMESTAMP           NOT NULL,
    status                  VARCHAR(15)         NOT NULL,
    vedtak_id_bidrag_vedtak INTEGER,
    opprettet_timestamp     TIMESTAMP           NOT NULL,
    endret_timestamp        TIMESTAMP
);

CREATE UNIQUE INDEX XPKT_VEDTAK_OVERFORING
    ON T_VEDTAK_OVERFORING (id);

CREATE UNIQUE INDEX XIE4T_VEDTAK_OVERFORING
    ON T_VEDTAK_OVERFORING(sokn_id);

CREATE UNIQUE INDEX XIE5T_VEDTAK_OVERFORING
    ON T_VEDTAK_OVERFORING(rolle_hist_id);

ALTER TABLE T_VEDTAK_OVERFORING ADD COLUMN notat VARCHAR(255);

ALTER TABLE T_VEDTAK_OVERFORING ADD COLUMN vedtak_overfort_med_grunnlag TIMESTAMP;
