version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: x-access-token
    password: no-secret-required
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
    scope: "@navikt"
updates:
  - package-ecosystem: "npm"
    directories:
      - "/util/bidrag-cli"
      - "/util/bidrag-cloudfunctions/postgres-auditlog"
      - "/apps/bidrag-dokumentasjon/frontend/bidrag-dokumentasjon"
    registries:
      - "npm-github"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "[dependency] "
  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/apps/*"
      - "/libs/*"
      - "/libs/bidrag-felles/*"
      - "/libs/bidrag-beregn-felles/*"
    cooldown:
      default-days: 7
    registries:
      - "maven-github"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    groups:
      maven-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "[dependency] "
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/apps/*"
      - "/util/bidrag-cloudfunctions/postgres-auditlog"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "[docker] "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "[github-actions] "
