CREATE TABLE IF NOT EXISTS endre_mottaker
(
    id                            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    vedtak_id                     integer   NOT NULL,
    saksnummer                    text      NOT NULL,
    barn_ident                    text      NOT NULL,
    ny_mottaker_ident             text      NOT NULL,
    overfort_til_skatt_tidspunkt  timestamp,
    godkjent_av_skatt_tidspunkt   timestamp,
    feilmelding_fra_skatt         text,
    opprettet_tidspunkt           timestamp NOT NULL DEFAULT current_timestamp
);

CREATE UNIQUE INDEX endre_mottaker_vedtak_barn_unique
    ON endre_mottaker (vedtak_id, barn_ident);

CREATE INDEX endre_mottaker_sak_barn_opprettet_index
    ON endre_mottaker (saksnummer, barn_ident, opprettet_tidspunkt, id)
    WHERE godkjent_av_skatt_tidspunkt IS NULL;
