CREATE TABLE IF NOT EXISTS endre_mottaker
(
    id                            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    vedtak_id                     integer   NOT NULL,
    saksnummer                    text      NOT NULL,
    barn_ident                    text      NOT NULL,
    ny_mottaker_ident             text      NOT NULL,
    overfort_til_skatt_tidspunkt  timestamp,
    godkjent_av_skatt_tidspunkt   timestamp,
    feilmelding_fra_skatt         text,
    opprettet_tidspunkt           timestamp NOT NULL DEFAULT current_timestamp
);

-- Brukes for å finne nyeste rad per (saksnummer, barn_ident) ved resending og varsling.
CREATE INDEX endre_mottaker_sak_barn_opprettet_index ON endre_mottaker (saksnummer, barn_ident, opprettet_tidspunkt DESC);

-- Delindeks for raskt oppslag av rader som ikke er godkjent av skatt enda.
CREATE INDEX endre_mottaker_ikke_godkjent_index ON endre_mottaker (saksnummer, barn_ident)
    WHERE godkjent_av_skatt_tidspunkt IS NULL;

