CREATE TABLE driftsmelding
(
    id                  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    opprettet_tidspunkt TIMESTAMP DEFAULT now() NOT NULL,
    aktiv_fra_tidspunkt TIMESTAMP,
    aktiv_til_tidspunkt TIMESTAMP,
    opprettet_av_navn   text                    NOT NULL,
    opprettet_av        text                    NOT NULL,
    tittel              text                    NOT NULL,
    innhold             text                    NOT NULL
);

alter table lest_av_bruker
    add column if not exists driftsmelding_id bigint REFERENCES driftsmelding (id)