management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

springdoc:
  packages-to-scan: no.nav.bidrag.admin.api
  swagger-ui:
    path: /
    display-request-duration: true
    try-it-out-enabled: true
spring.main.banner-mode: off
---
spring.config.activate.on-profile: nais,lokal-nais
spring:
  application:
    name: "bidrag-admin-fss"
  datasource:
    url: jdbc:db2://${DB_HOST}:${DB_PORT}/${DB_NAME}:currentSchema=${BISYS_DB_SCHEMA};
    username: ${BISYS_DB_USERNAME}
    password: ${BISYS_DB_PASSWORD}
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    database-platform: org.hibernate.dialect.DB2zDialect
    open-in-view: false

no.nav.security.jwt:
  issuer.aad:
    discovery_url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

BIDRAG_BOT_SLACK_OAUTH_TOKEN: ${MR_B_SLACK_OAUTH_TOKEN}
