name: bidrag-person-hendelse

ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
  - https://bidrag-person-hendelse.intern.nav.no

replicas:
  min: 2
  max: 2
limits:
  memory: 2048Mi
requests:
  memory: 1024Mi
  cpu: 200m
kafka:
  pool: nav-prod

env:
  SPRING_PROFILES_ACTIVE: prod, nais
  BIDRAG_PERSON_HOST: bidrag-person.prod-fss-pub.nais.io
  MQ_HOST: mpls04.adeo.no
  MQ_PORT: 1414
  # TODO: Avro 1.12-whitelist for spesifikke lesere. Bør strammes inn fra "*" til faktiske pakker.
  AVRO_SERIALIZABLE_PACKAGES: "*"
database:
  tier: db-custom-1-3840
  navn: person-hendelse-prod
  auditlog: "on"
