CREATE TABLE IF NOT EXISTS valutakursgrunnlag
(
    valutakursgrunnlag_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp NOT NULL,
    bruk_til timestamp NOT NULL,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    oppdatert_tidspunkt timestamp DEFAULT now() NOT NULL,
    kurs numeric(38, 16),
    multiplikator integer,
    basisvaluta varchar(3) NOT NULL,
    kvoteringsvaluta varchar(3) NOT NULL,
    feilet_henting boolean DEFAULT false NOT NULL,
    status varchar(10) NOT NULL,
    CONSTRAINT valutakursgrunnlag_pkey PRIMARY KEY (valutakursgrunnlag_id),
    CONSTRAINT valutakursgrunnlag_periode_unique UNIQUE (basisvaluta, bruk_fra),
    CONSTRAINT valutakursgrunnlag_status_check CHECK (status IN ('FEILET', 'HENTET', 'OVERSTYRT')),
    CONSTRAINT valutakursgrunnlag_halvar_check CHECK (
        EXTRACT(MONTH FROM bruk_fra) IN (1, 7)
        AND EXTRACT(DAY FROM bruk_fra) = 1
        AND bruk_fra = date_trunc('day', bruk_fra)
        AND bruk_til = bruk_fra + INTERVAL '6 months'
    )
)
    TABLESPACE pg_default;

CREATE OR REPLACE FUNCTION oppdater_valutakursgrunnlag_tidspunkt()
RETURNS trigger AS $$
BEGIN
    NEW.oppdatert_tidspunkt = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER valutakursgrunnlag_oppdatert_tidspunkt
    BEFORE UPDATE ON valutakursgrunnlag
    FOR EACH ROW
    EXECUTE FUNCTION oppdater_valutakursgrunnlag_tidspunkt();