-- Table: valutakursgrunnlag

-- DROP TABLE valutakursgrunnlag;

CREATE TABLE IF NOT EXISTS valutakursgrunnlag
(
    valutakursgrunnlag_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    kurs double precision NOT NULL,
    multiplikator integer NOT NULL,
    basisvalutakode character varying(3) NOT NULL,
    kvoteringsvalutakode character varying(3) NOT NULL,
    CONSTRAINT valutakursgrunnlag_pkey PRIMARY KEY (valutakursgrunnlag_id),
)

    TABLESPACE pg_default;