name: Deploy alerts to prod
on:
  push:
    branches:
      - main
    paths:
      - 'bidrag-alerts-prod.yaml'
      - '**/deploy_prod.yml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: bidrag-alerts-prod.yaml
      - name: deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: bidrag-alerts-prod.yaml