name: bidrag-admin-fss
ingresses:
  - https://bidrag-admin-fss.intern.dev.nav.no
bisys_url: b27wasl00799.preprod.local
limits:
  memory: 2048Mi
requests:
  cpu: 117m
  memory: 512Mi
replicas:
  max: 1
  min: 1
env:
  BISYS_URL: b27wasl00799.preprod.local
  SLACK_CHANNEL_ID: dummy # Skal ikke følge opp i dev
  DB_HOST: ztest.test.local
  DB_PORT: 5025
  DB_NAME: QDB2
  BBM_DB_SCHEMA: BI460Q2
  BISYS_DB_SCHEMA: BI464Q2
  JIRA_URL: dummy
azure_access_inbound:
  - application: bidrag-ui
    namespace: bidrag
    cluster: dev-fss
  - application: bidrag-ui-feature
    namespace: bidrag
    cluster: dev-fss