CREATE TABLE IF NOT EXISTS sak
(
    id                  integer                 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 20 ),
    saksnummer          text                    NOT NULL,
    sak                 jsonb                   NOT NULL,
    kategori            text                    NOT NULL,
    eierfogd            text                    NOT NULL,
    saksstatus          text                    NOT NULL,
    arbeidsfordeling    text                    NOT NULL,
    opprettet_dato      date                    NOT NULL,
    avsluttet           boolean   DEFAULT false NOT NULL,
    opprettet_tidspunkt timestamp DEFAULT now() NOT NULL,
    endret_tidspunkt    timestamp DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sak_saksnummer ON sak (saksnummer);

GRANT ALL PRIVILEGES ON TABLE public.sak TO cloudsqliamuser;
