name: bidrag-oppgave
ingresses:
  - https://bidrag-oppgave.intern.nav.no
limits:
  memory: 1Gi
requests:
  memory: 256Mi
replicas:
  max: 2
  min: 2
env:
  APP_OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io
  APP_OPPGAVE_AUDIENCE: api://prod-fss.oppgavehandtering.oppgave/.default

inbound:
  rules:
    - application: bidrag-frontend
      namespace: bidrag
      cluster: prod-gcp

outbound:
  rules:
#    - application: bidrag-admin
  external:
    - oppgave.prod-fss-pub.nais.io