BIDRAG_PERSON_URL=https://junit.adeo.no/bdperson
BREVSERVER_URL=http://brevserver
BREVSERVER_NAIS_URL=http://brevserver-nais
OPPGAVE_OPPGAVER_URL=https://oppgave.nais.preprod.local/api/v1/oppgaver
NORG2_API_V1_URL=https://norg
BIDRAG_ORGANISASJON_URL=https://bidrag-organisasjon
