spring:
  application:
    name: bidrag-oppgave
  security:
    oauth2:
      # Validering av innkommende Azure AD-brukertoken
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}
      # OBO token exchange mot oppgave-api (team oppgave)
      client:
        registration:
          oppgave-api-obo:
            provider: azure
            client-id: ${AZURE_APP_CLIENT_ID}
            client-authentication-method: private_key_jwt
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: ${OPPGAVE_API_SCOPE}
        provider:
          azure:
            token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

oppgave-api:
  base-url: ${OPPGAVE_API_URL}
springdoc:
  packages-to-scan: no.nav.bidrag.oppgave.controller
  swagger-ui:
    path: /
    display-request-duration: true
    try-it-out-enabled: true

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /internal
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

