name: Bidrag-reisekostnad-api
on:
  workflow_dispatch:
    inputs:
      miljo:
        description: "Miljø som skal deployes til"
        required: true
        type: choice
        options:
          - prod
          - q1
  pull_request:
    types: [labeled, unlabeled]
    paths:
      - 'pom.xml'
      - 'libs/bidrag-felles/**'
      - '.nais/bidrag-reisekostnad-api/**.yaml'
      - 'apps/bidrag-reisekostnad-api/**'
  push:
    branches:
      - '**'
      - '!dependabot/**'
    paths:
      - 'pom.xml'
      - 'libs/bidrag-felles/**'
      - '.nais/bidrag-reisekostnad-api/**.yaml'
      - 'apps/bidrag-reisekostnad-api/**'

jobs:
  detect_changes:
    name: "Sjekk om appen faktisk er endret"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/utled-app-endringer
        id: detect

  finn_miljo:
    name: "Bestem hvilke miljø som skal deployes"
    needs: detect_changes
    if: needs.detect_changes.outputs.changed == 'true' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "read"
    outputs:
      deploy_q1: ${{ steps.finn.outputs.deploy_q1 }}
      deploy_prod: ${{ steps.finn.outputs.deploy_prod }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/finn-deploy-miljo
        id: finn
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dispatch-miljo: ${{ inputs.miljo }}

  bygg_test_og_deploy:
    name: "Bygg, test og deploy"
    needs: finn_miljo
    permissions:
      contents: "write"
      id-token: "write"
    uses: ./.github/workflows/bygg_og_deploy.yaml
    secrets: inherit
    with:
      runner: ubuntu-latest-4-cores
      nais_hovedfil_navn: bidrag-reisekostnad-api/nais.yaml
      nais_variabler_filnavn_q1: bidrag-reisekostnad-api/preprod.yaml
      deploy_q1: ${{ needs.finn_miljo.outputs.deploy_q1 == 'true' }}
      nais_variabler_filnavn_prod: bidrag-reisekostnad-api/prod.yaml
      deploy_prod: ${{ needs.finn_miljo.outputs.deploy_prod == 'true' }}
      maven_options: -B -fae -pl apps/bidrag-reisekostnad-api
      maven_cache_paths: |
        pom.xml
        apps/bidrag-reisekostnad-api/pom.xml
      ktlint_paths: apps/bidrag-reisekostnad-api/src/**/*.kt
      docker_context: ./apps/bidrag-reisekostnad-api
      image_suffix: bidrag-reisekostnad-api
      tag: bidrag-reisekostnad-api
