name: Bidrag-kafka
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '.nais/bidrag-kafka/**.yaml'
      - 'apps/bidrag-kafka/**'

# Felles workflow for alle kafka.nais.io/v1 Topic-manifester i .nais/bidrag-kafka/topics,
jobs:
  detect_changes:
    name: "Sjekk om appen faktisk er endret"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/utled-app-endringer
        id: detect

  deploy_dev:
    needs: detect_changes
    if: needs.detect_changes.outputs.changed == 'true' && github.ref != 'refs/heads/main'
    name: "Set up kafka topics i dev"
    concurrency:
      group: deploy-bidrag-kafka-dev-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up kafka topics i dev-gcp
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/bidrag-kafka/topics/journalpost.yaml,.nais/bidrag-kafka/topics/journalpost-feature.yaml,.nais/bidrag-kafka/topics/dokument-dev.yaml,.nais/bidrag-kafka/topics/dokument-feature.yaml,.nais/bidrag-kafka/topics/sak-q1.yaml,.nais/bidrag-kafka/topics/sak-q2.yaml,.nais/bidrag-kafka/topics/vedtak-q1.yaml,.nais/bidrag-kafka/topics/vedtak-q2.yaml,.nais/bidrag-kafka/topics/vedtak-q4.yaml,.nais/bidrag-kafka/topics/samhandler-q1.yaml,.nais/bidrag-kafka/topics/samhandler-q2.yaml,.nais/bidrag-kafka/topics/samhandler-q4.yaml,.nais/bidrag-kafka/topics/statistikk-q2.yaml,.nais/bidrag-kafka/topics/vedtaksforslag-q1.yaml,.nais/bidrag-kafka/topics/vedtaksforslag-q2.yaml,.nais/bidrag-kafka/topics/vedtaksforslag-q4.yaml,.nais/bidrag-kafka/topics/statistikk-bidrag-q2.yaml,.nais/bidrag-kafka/topics/behandling-q2.yaml,.nais/bidrag-kafka/topics/behandling-q1.yaml,.nais/bidrag-kafka/topics/statistikk-saerbidrag-q2.yaml,.nais/bidrag-kafka/topics/personhendelse-preprod.yaml

  deploy_prod:
    needs: detect_changes
    if: needs.detect_changes.outputs.changed == 'true' && github.ref == 'refs/heads/main'
    name: "Set up kafka topics i prod"
    concurrency:
      group: deploy-bidrag-kafka-prod-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up kafka topics i prod-gcp
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/bidrag-kafka/topics/journalpost-prod.yaml,.nais/bidrag-kafka/topics/vedtak-prod.yaml,.nais/bidrag-kafka/topics/dokument-prod.yaml,.nais/bidrag-kafka/topics/sak-prod.yaml,.nais/bidrag-kafka/topics/samhandler-prod.yaml,.nais/bidrag-kafka/topics/statistikk-prod.yaml,.nais/bidrag-kafka/topics/vedtaksforslag-prod.yaml,.nais/bidrag-kafka/topics/statistikk-bidrag-prod.yaml,.nais/bidrag-kafka/topics/behandling-prod.yaml,.nais/bidrag-kafka/topics/statistikk-saerbidrag-prod.yaml,.nais/bidrag-kafka/topics/personhendelse-prod.yaml
