name: Bidrag-elin-stub
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'
    paths:
      - '.nais/bidrag-elin-stub/**.yaml'
#      - '.github/workflows/bidrag-elin-stub.yaml' //TODO(Slå på etter migrering)
#     - 'pom.xml' //TODO(Slå på etter migrering)
      - 'apps/bidrag-elin-stub/**'

jobs:
  detect_changes:
    name: "Sjekk om appen faktisk er endret"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/utled-app-endringer
        id: detect

  build_and_deploy:
    needs: detect_changes
    if: needs.detect_changes.outputs.changed == 'true'
    name: "Build and deploy"
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/bygg_og_deploy.yaml
    secrets: inherit
    with:
      maven_options: -B -fae -pl apps/bidrag-elin-stub -am
      maven_cache_paths: |
        pom.xml
        apps/bidrag-elin-stub/pom.xml
      ktlint_paths: apps/bidrag-elin-stub/src/**/*.kt
      docker_context: ./apps/bidrag-elin-stub
      nais_variabler_filnavn: bidrag-elin-stub/main.yaml
      nais_hovedfil_navn: bidrag-elin-stub/nais.yaml
      image_suffix: bidrag-elin-stub
