name: Bidrag-oppgave
on:
  workflow_dispatch:
    inputs:
      miljo:
        description: "Miljø som skal deployes til"
        required: true
        type: choice
        options:
          - prod
          - q1
          - q2
      hopp_over_tester:
        description: >-
          Hopp over tester og ktlint for å tvinge gjennom en deploy.
          Fungerer kun for q1/q2 - ignoreres for prod.
        required: false
        type: boolean
        default: false
  push:
    branches:
      - 'main'
    paths:
      - 'pom.xml'
      - '.nais/bidrag-oppgave/**.yaml'
      - 'apps/bidrag-oppgave/**'
      - 'libs/bidrag-oppgave-dto/**'
      - 'libs/bidrag-oppgave-client/**'
  pull_request:
    paths:
      - 'pom.xml'
      - '.nais/bidrag-oppgave/**.yaml'
      - 'apps/bidrag-oppgave/**'
      - 'libs/bidrag-oppgave-dto/**'
      - 'libs/bidrag-oppgave-client/**'

jobs:
  detect_changes:
    name: "Sjekk om appen faktisk er endret"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/utled-app-endringer
        id: detect

  bygg_test_og_deploy:
    name: "Bygg, test og deploy"
    needs: detect_changes
    if: needs.detect_changes.outputs.changed == 'true'
    permissions:
      contents: "write"
      id-token: "write"
    uses: ./.github/workflows/bygg_og_deploy.yaml
    secrets: inherit
    with:
      nais_hovedfil_navn: bidrag-oppgave/nais.yaml
      nais_variabler_filnavn_q1: bidrag-oppgave/q1.yaml
      deploy_q1: ${{ github.event_name == 'workflow_dispatch' && inputs.miljo == 'q1' }}
      nais_variabler_filnavn_q2: bidrag-oppgave/q2.yaml
      deploy_q2: ${{ github.event_name == 'workflow_dispatch' && inputs.miljo == 'q2' }}
      nais_variabler_filnavn_prod: bidrag-oppgave/prod.yaml
      deploy_prod: ${{ (github.event_name == 'workflow_dispatch' && inputs.miljo == 'prod') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
      skip_tester: ${{ inputs.hopp_over_tester == true && (inputs.miljo == 'q1' || inputs.miljo == 'q2') }}
      maven_options: -B -fae -pl apps/bidrag-oppgave -am
      maven_cache_paths: |
        pom.xml
        apps/bidrag-oppgave/pom.xml
      ktlint_paths: apps/bidrag-oppgave/src/**/*.kt libs/bidrag-oppgave-dto/src/**/*.kt libs/bidrag-oppgave-client/src/**/*.kt
      docker_context: ./apps/bidrag-oppgave
      image_suffix: bidrag-oppgave
      tag: bidrag-oppgave
