name: Bidrag-admin-fss
on:
  workflow_dispatch:
    inputs:
      miljo:
        description: "Miljø som skal deployes til"
        required: true
        type: choice
        options:
          - prod
          - q1
  push:
    branches:
      - '**'
      - '!dependabot/**'
    paths:
      - 'pom.xml'
      - 'libs/bidrag-felles/**'
      - '.nais/bidrag-admin-fss/**.yaml'
      - 'apps/bidrag-admin/pom.xml'
      - 'apps/bidrag-admin/bidrag-admin-fss/**'

jobs:
  detect_changes:
    name: "Sjekk om appen faktisk er endret"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/utled-app-endringer
        id: detect

  bygg_test_og_deploy:
    name: "Bygg, test og deploy"
    needs: detect_changes
    if: needs.detect_changes.outputs.changed == 'true' && github.actor != 'dependabot[bot]'
    permissions:
      contents: "write"
      id-token: "write"
    uses: ./.github/workflows/bygg_og_deploy.yaml
    secrets: inherit
    with:
      nais_cluster: fss
      nais_hovedfil_navn: bidrag-admin-fss/nais.yaml
      nais_variabler_filnavn_q1: bidrag-admin-fss/dev.yaml
      deploy_q1: ${{ github.event_name == 'workflow_dispatch' && inputs.miljo == 'q1' }}
      nais_variabler_filnavn_prod: bidrag-admin-fss/prod.yaml
      deploy_prod: ${{ (github.event_name == 'workflow_dispatch' && inputs.miljo == 'prod') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
      maven_options: -B -fae -pl apps/bidrag-admin/bidrag-admin-fss
      maven_cache_paths: |
        pom.xml
        apps/bidrag-admin/pom.xml
        apps/bidrag-admin/bidrag-admin-fss/pom.xml
      ktlint_paths: apps/bidrag-admin/bidrag-admin-fss/src/**/*.kt
      docker_context: ./apps/bidrag-admin/bidrag-admin-fss
      dockerfile_with_path: ./apps/bidrag-admin/bidrag-admin-fss/Dockerfile
      image_suffix: bidrag-admin-fss
      tag: bidrag-admin-fss
