name: Bidrag-elin-stub
on:
  workflow_call:
    inputs:
      bibliotekartefakt:
        description: Navn på artefaktet med ferdige biblioteker fra bygg-apper.
        required: false
        type: string
        default: ''
      miljo:
        required: false
        type: string
        default: ''
      hopp_over_tester:
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      miljo:
        description: "Miljø som skal deployes til"
        required: true
        type: choice
        options:
          - q2
      hopp_over_tester:
        description: >-
          Hopp over tester og ktlint for å tvinge gjennom en deploy.
          Fungerer kun for q1/q2 - ignoreres for prod.
        required: false
        type: boolean
        default: false

env:
  APP_PATHS: |
    pom.xml
    libs/bidrag-felles/**
    .nais/bidrag-elin-stub/**.yaml
    apps/bidrag-elin-stub/**

jobs:
  bygg_test_og_deploy:
    name: "Bygg, test og deploy"
    permissions:
      contents: "write"
      id-token: "write"
    uses: ./.github/workflows/bygg_og_deploy.yaml
    secrets: inherit
    with:
      bibliotekartefakt: ${{ inputs.bibliotekartefakt }}
      nais_hovedfil_navn: bidrag-elin-stub/nais.yaml
      nais_variabler_filnavn_q2: bidrag-elin-stub/main.yaml
      deploy_q2: ${{ github.event_name == 'workflow_dispatch' && inputs.miljo == 'q2' }}
      skip_tester: ${{ inputs.hopp_over_tester == true && (inputs.miljo == 'q1' || inputs.miljo == 'q2') }}
      maven_options: -B -fae -pl apps/bidrag-elin-stub
      maven_cache_paths: |
        pom.xml
        apps/bidrag-elin-stub/pom.xml
      ktlint_paths: apps/bidrag-elin-stub/src/**/*.kt
      docker_context: ./apps/bidrag-elin-stub
      image_suffix: bidrag-elin-stub
