name: Tag utgivelse
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: Docker image tag som ble deployet til miljø
      app_navn:
        required: false
        type: string
        description: Navn på app/modul. Brukes som prefiks på git-taggen for å unngå at flere apper i dette monorepoet kolliderer på samme tag når de bygges fra samme commit.

jobs:
  tag_utgivelse:
    runs-on: ubuntu-latest
    name: Tag release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Push latest image tag as github tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.tag }}
          tag_prefix: ${{ inputs.app_navn != '' && format('{0}-v', inputs.app_navn) || 'v' }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
